# Builder stage 

FROM python:3.9-alpine AS build

WORKDIR /app 

RUN apk update && apk upgrade && apk add --no-cache \ 
    gcc \ 
    musl-dev \ 
    mariadb-dev \ 
    pkgconfig 

COPY requirements.txt . 

RUN pip install --upgrade pip 

# Install dependencies into a separate directory

RUN pip install --no-cache-dir \
    --prefix=/install \
    -r requirements.txt 


# Runner stage

FROM python:3.9-alpine AS runner

WORKDIR /app

# Only runtime dependency needed for mysqlclient

RUN apk add --no-cache \
    mariadb-connector-c 

# Copy installed Python packages from builder

COPY --from=build /install /usr/local

# Copy application code

COPY . . 

RUN adduser -D appuser && chown -R appuser /app 

USER appuser

CMD ["gunicorn","--bind","0.0.0.0:5000", "app:app"]
